name: CI/CD

on:
  push: # A push indicates that a PR is merged and CD should be triggered
    branches:
      - main
      - alpha
  pull_request: # For PRs, we run CI, which is the same as CD without the release step(s)
    branches:
      - main
      - alpha

jobs:
  # A setup job to define the matricies that will be used across all of the jobs in this workflow
  setup:
    runs-on: ubuntu-latest
    outputs:
      # The packages that use Uniffi bindings
      uniffi_packages: ${{ steps.set_uniffi_packages.outputs.uniffi_packages }}
      app_token: ${{ steps.set_app_token.outputs.token }}
    steps:
      - id: set_uniffi_packages
        run: echo 'uniffi_packages=["algokit_transact"]' >> $GITHUB_OUTPUT
      - uses: actions/create-github-app-token@v1
        id: set_app_token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_SK }}


  python_uniffi_ci_cd:
    needs: setup
    uses: ./.github/workflows/python_uniffi_ci_cd.yml
    strategy:
      matrix:
        crate: ${{ fromJSON(needs.setup.outputs.uniffi_packages) }}
    with:
      crate: ${{ matrix.crate }}
      release: ${{ github.event_name == 'push' }}
    secrets:
      GH_TOKEN: ${{ needs.setup.outputs.app_token }}
