name: Python CI/CD

on:
  push:
    branches:
      - main
      - alpha
  pull_request:
    branches:
      - main
      - alpha

jobs:
  uniffi_ci_cd:
    uses: ./.github/workflows/python_uniffi_ci_cd.yml
    strategy:
      matrix:
        crate: [algokit_transact]
    with:
      crate: ${{ matrix.crate }}
      release: ${{ github.event_name == 'push' }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
